server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis.cfg.xml
  type-aliases-package: com.hx.applyaspect.model


spring:
  application:
    name: applyaspect
  datasource:
    url: jdbc:mysql://localhost:3306/applyaspect?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 8899
    driver-class-name: com.mysql.jdbc.Driver